!$THEME = "drawio"

<style>
    --green: #d5e8d4
    --green-border: #82b366
    --yellow: #fff2cc
    --dark-yellow: #f2e5c1
    --yellow-border: #d6b656
    --light-yellow: #f9f7ed
    --blue: #dae8fc
    --blue-border: #6c8ebf
    --red: #f8cecc
    --red-border: #b85450
    --violet: #dfd5e6
    --violet-border: #9175a3

    root {
      FontName Helvetica
      FontSize 12
      LineThickness 1.3
    }

    sequenceDiagram {
        group {
          LineThickness 1.3
        }

    	groupHeader {
    	  BackGroundColor var(--violet)
    	}

    	note {
    	  LineColor var(--dark-yellow)
    	  BackGroundColor var(--light-yellow)
    	}

        participant,actor,boundary,control,entity,queue,collections {
          LineColor var(--green-border)
          BackgroundColor var(--green)
        }

        database,queue {
          LineColor var(--yellow-border)
          BackgroundColor var(--yellow)
        }

        entity {
          LineColor var(--red-border)
          BackgroundColor var(--red)
        }
    }

    .decides what to do {
        LineColor var(--blue-border)
        BackGroundColor var(--blue)
    }
}
</style>

skinparam maxMessageSize 150
skinparam wrapWidth 150
